# Generated by Django 5.0.4 on 2024-04-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='dept_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
