# Generated by Django 5.0.4 on 2024-04-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_booking_p_name_alter_doctors_doc_dept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
