# Generated by Django 5.0.4 on 2024-04-25 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0008_doctors_group_alter_doctors_doc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
