# Generated by Django 5.0.4 on 2024-04-25 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_doctors_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doc_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.departments'),
        ),
    ]
