# Generated by Django 5.0.4 on 2024-04-25 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_doctors_doc_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='group',
        ),
    ]
